# Generated by Django 5.0.4 on 2024-04-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cliente_important'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='price',
            new_name='total',
        ),
    ]
